language: objective-c
osx_image: xcode8
before_install:
  - sudo motion update
  - motion repo
  - bundle install
  - pod setup
  - bundle exec rake clean
  - bundle exec rake pod:install
script: bundle exec rake spec
env:
  global:
  - COCOAPODS_NO_REPO_UPDATE_OUTPUT=true
