language: objective-c
cache:
  bundler: true
  cocoapods: true
  directories: []
branches:
  only:
    - master
    - devel
before_install:
  - motion update --check || sudo motion update; true
  - (motion --version)
  - (ruby --version)
script:
  - bundle exec rake pod:install
  - bundle exec rake clean spec
env:
  global:
  - COCOAPODS_NO_REPO_UPDATE_OUTPUT=true
